# srv.yml
server:
  SERVER_IP: localhost
  SERVER_PORT: 333
  TIMEOUT: 30000

database:
  URL: jdbc:mysql://localhost:3306/ticketing?useUnicode=true&characterEncoding=UTF-8
  USER: root
  PASSWORD: '123'
